# 1.With a given integral number n, write a function to generate a dictionary that contains (i, i*i) such that is an integral number between 1 and n (both included).
1...Number should not be less than 0 and should not be greater than 100.
2..Calculate square of all number from 1 to n and store in dict

In [1]:
def  squareOfNumbers(num):
    t = {}
    if num > 0 and num <= 100:
        for x in range(1,num+1):
            t.update({x: pow(x, 2)})
    return t

In [5]:
squareOfNumbers(5)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25}

# 2.Write a program that accepts a sentence and calculate the number of letters and digits.

In [6]:
def letterAndDigit(string):
    count1=0
    count2=0
    for character in string:
        if character.isdigit():
            count1 += 1
        elif character.isalpha():
            count2 += 1
        elif character == " ":
            pass

    return {"DIGITS": count1 ,"LETTERS": count2}

In [7]:
letterAndDigit('world! 234')

{'DIGITS': 3, 'LETTERS': 5}

# 3.With a given integer number n, write a function to get all even numbers starting from 1

In [8]:
def get_even_numbers(num):
    lst = [i for i in range(2,num + 1,2) if i > 0]
    return lst

In [9]:
get_even_numbers(12)

[2, 4, 6, 8, 10, 12]

# 4.Write a function to concatenate two dictionaries to create a new one.

In [10]:
def solution(dic1, dic2):
    d = dic1.copy()
    d.update(dic2)
    return d

In [11]:
solution({1: 10, 2: 20}, {3: 30, 4: 40})

{1: 10, 2: 20, 3: 30, 4: 40}

# 5.Define a function to check if a given key already exists in a dictionary.

In [12]:
def solution(dic1, key1):
    '''Enter Code Here'''
    count = 0
    for k in dic1.keys():
        if k == key1:
            count += 1
    if count == 0:
        return False
    else:
        return True

In [13]:
solution({1:10,2:20,3:30,4:40},3)

True

# 6.Define a function that takes a dictionary as a parameter and iterates over its key:value pairs. The Function should return a sorted list containing tuples of the key-value pairs.

In [14]:
def solution(dic1):
    '''Enter code here'''
    l = [(k ,v) for k,v in dic1.items()]
    return l

In [15]:
solution({1: 10, 2: 20, 3: 30, 4: 40})

[(1, 10), (2, 20), (3, 30), (4, 40)]

# 7.Define a function that takes a dictionary as a parameter and returns the sum of all the values in it.

In [16]:
def solution(dic):
    '''Enter Code Here'''
    return sum(dic.values())

In [17]:
solution({1:10, 2:20, 3:30})

60

# 8.Define a function that takes two parameters: a dictionary and a key. Then remove the key from the dictionary if it is present. Return the dictionary.

In [18]:
def solution(dic1, key1):
    '''Enter Code Here'''
    if key1 in dic1:
        del dic1[key1]
    return dic1

In [19]:
solution({1:10, 2:20, 3:30}, 2)

{1: 10, 3: 30}

# 9.Define a function that takes two lists as parameter and returns a dictionary after combining the lists.

In [20]:
def solution(keys, values):
    '''Enter Code Here'''
    z = dict(zip(keys,values))
    return z

In [21]:
solution([1, 2, 3], [10, 20, 30])

{1: 10, 2: 20, 3: 30}

# 10.Define a function that takes a dictionary as a parameter and returns a sorted list of the keys of the dictionary

In [22]:
def solution(dic):
    """Enter Code Here"""
    return sorted(list(dic.keys()))

In [23]:
solution({1: 10, 4: 40, 2: 20, 3: 30})

[1, 2, 3, 4]

# 11.Define a function that takes a dictionary as a parameter and returns a tuple of the maximum and minimum value.

In [24]:
def solution(dic):
    "Enter Code here"
    return (max(dic.values()),min(dic.values()))

In [25]:
solution({'a': 1, 'b': 2, 'c': 35})

(35, 1)

# 12.Define a function that takes a list of numbers as a parameter and returns the second smallest number in the list.

In [30]:
def solution(list1):
    """Enter Code Here"""
    list1.sort()
    return list1[1]

In [31]:
solution([1, 2, -8, -2, 0])

-2

# 13.Define a function that takes two parameters: a list of numbers, a number The function should first sort the list and then insert the number into the list so that the list still remains sorted. Function should return the updated list

In [32]:
import bisect

def solution(list_of_nums, num):
    """Enter Code Here"""
    list_of_nums.sort()
    bisect.insort(list_of_nums,num)
    return list_of_nums

In [33]:
solution([1, 2, 3, 5, 6], 4)

[1, 2, 3, 4, 5, 6]

# 14.With a given integer number n, write a function to get array of all prime numbers from 1 to n.

In [35]:
def get_prime_numbers(n):
    prime=[]
    if n > 1:
        for i in range(2,n):
            for j in range(2,i):
                if (i%j==0):
                        break
            else:
                prime.append(i)
    else:
        if n<=1:
            print ("Number is less than one")

    return prime

In [36]:
get_prime_numbers(20)

[2, 3, 5, 7, 11, 13, 17, 19]

# 15.Define a function that takes 3 parameters(all positive integers) in this order: num1, num2, end_num
# Function should return a list of all numbers less than end_num that are divisible by both num1 and num2.

In [37]:
def solution(num1, num2, end_num):
    """Enter Code Here"""
    list1 = [x for x in range(1,end_num+1) if x % num1==0 and x%num2==0 ]
    return list1

In [38]:
solution(4, 6, 37)

[12, 24, 36]

# 16.Define a function that returns the following pattern in a string (alphabet 'G'):

                          ***                                                                   
                         *   *                                                                  
                         *                                                                      
                         * ***                                                                  
                         *   *                                                                  
                         *   *                                                                  
                          ***   


In [44]:
def solution():
    """Enter Code Here"""
    a=" *** "
    b="*   *"
    c="*    "
    d="* ***"
    e="*   *"
    f="*   *"
    g=" *** "
    print (a +"\n"+b+"\n"+c+"\n"+d+"\n"+e+"\n"+f+"\n"+g)

In [45]:
solution()

 *** 
*   *
*    
* ***
*   *
*   *
 *** 


# 17.Write a Python program to count the number of even and odd numbers from a series of numbers

In [46]:
def solution(list_of_nums):
    """Enter Code Here"""
    count1=0
    count2=0
    for index in list_of_nums:
        if index%2 == 0:
            count1 += 1
        else:
            count2 += 1


    return {"ODD": count2 ,"EVEN": count1}

In [47]:
solution([1, 2, 3, 5, 8, 9])

{'ODD': 4, 'EVEN': 2}

# 18.Remove duplicate from following list

In [48]:
def solution(list):
    unique = []
    for x in list:
        if x not in unique:
            unique.append(x)
    return unique

In [49]:
solution([3,4,3,5,4])

[3, 4, 5]

# 19.Find out whether a list is a palindrome

In [50]:
def solution(list):
    if list == list[::-1]:
        return True
    else:
        return False

In [51]:
solution(['n','i','t','i','n'])

True

# 20.Given this nest dictionary grab the word "hello".

In [52]:
def solution(dic):
    last_index_of_target = dic['k1'][3]['tricky'][3]['target'][3]


    return last_index_of_target


dic = {'k1': [1, 2, 3, {'tricky': ['oh', 'man', 'inception', {'target': [1, 2, 3, 'hello']}]}]}
dic['k1'][3]['tricky'][3]['target'][3]

'hello'

# 21.Write a Python script to sort (ascending and descending) a dictionary by key

In [53]:
import operator


def solution_asc(dic):
    return sorted(dic.items())

def solution_desc(dic):
    return sorted(dic.items(),key=operator.itemgetter(0),reverse=True)

In [56]:
solution_asc({'a': 2, 'c': 4, 'd': 3, 'b': 1, 'e': 0})

[('a', 2), ('b', 1), ('c', 4), ('d', 3), ('e', 0)]

In [57]:
solution_desc({'a': 2, 'c': 4, 'd': 3, 'b': 1, 'e': 0})

[('e', 0), ('d', 3), ('c', 4), ('b', 1), ('a', 2)]

# 22.Write a function to find pair sum in a list.

In [74]:
def pairSum(lst1,num1):
    final_list = []
    lst1.sort()
    lower = 0
    upper = len(lst1) -1
    while lower < upper:
        if lst1[lower] + lst1 [upper] == num1:
            lower +=1
            upper -=1
            final_list.append((lst1[lower],lst1[upper]))
        elif lst1[lower] + lst1 [upper] < num1:
             lower +=1
        else:
            upper -=1
        return final_list

In [81]:
pairSum([1,2,3,4,5,6,7,8,9],10)

[(2, 8)]

# 23.Write a Python program to combine two dictionary adding values for common keys.

In [82]:
def solution(d1, d2):
    d3 ={}
    for x,y in d1.items():
        if x in d2.keys():
            d3[x]=d1[x]+d2[x]
        else:
            d3[x]=d1[x]
    for x,y in d2.items():
        if x not in d1.keys():
            d3[x]=d2[x]
    return (d3)

In [83]:
solution({'a': 100, 'b': 200, 'c':300},{'a': 300, 'b': 200, 'd':400})

{'a': 400, 'b': 400, 'c': 300, 'd': 400}

# 24.Write a Python program to sum all the items in a list.

In [84]:
def solution(list_of_integers):
    sum_numbers = 0
    for number in list_of_integers:
        sum_numbers = number + sum_numbers 

    return sum_numbers

In [85]:
solution([2,3,5,8,11])

29

# 25.Write a Python program to generate all sublists of a list.

In [90]:
import itertools
def solution(a_list):
    sublist1 = []
    for i in range(0,len(a_list)+1):
        sublist1 += map(list,itertools.combinations(a_list,i))
    return sublist1

In [91]:
solution([10, 20, 30])

[[], [10], [20], [30], [10, 20], [10, 30], [20, 30], [10, 20, 30]]

# 26.Write a Python program to count the number of strings where the string length is 2 or more and the first and last character are same from a given list of strings

In [92]:
def solution(lis):
    count = 0
    for item in lis:
        if len(item)>=2 and item[0] == item[-1]:
            count +=1
    return count

In [96]:
solution(['abc', 'xyz', 'aba', 'dad', '1871'])

3

# 27.Write a Python program to get a list, sorted in increasing order by the last element in each tuple from a given list of non-empty tuples

In [97]:
def solution(list_of_tuples):
    return sorted(list_of_tuples,key=lambda x:x[1])

In [99]:
solution([(2, 55), (1, 25), (4, 45), (2, 30), (2, 1)])

[(2, 1), (1, 25), (2, 30), (4, 45), (2, 55)]

# 28.Write a Python function that takes two lists and returns True if they have at least one common member.

In [100]:
def solution(list1, list2):
    result = False
    for x in list1:
        if x in list2:
            result = True
            return result
    return result

In [101]:
solution([1,2,3,4,5],[5,6,7,8])

True

# 29.Write a Python program to create and display all combinations of letters, selecting each letter from a different key in a dictionary.

In [102]:
def solution(dic):
    list_of_combinations = []
    dic1 = dic['one']
    dic2 = dic['two']
    list_of_combinations = [dic1[i]+dic2[j] for i in range(0,len(dic1)) for j in range (0,len(dic2))]
    return list_of_combinations

In [103]:
solution({'one':['a','b'], 'two':['c','d']})

['ac', 'ad', 'bc', 'bd']

# 30.Flatten a shallow list(Return a combined list of above various lists.)

In [104]:
def solution(list):
    lis1=[]
    for sublist in list:
        for item in sublist:
            lis1.append(item)
    return lis1

In [105]:
solution([[1,2,3],[4,5],[6],[7],[8,9]])

[1, 2, 3, 4, 5, 6, 7, 8, 9]

# 31.Write a function that should count word occurance in file.

In [117]:
def countWord(filepath,word):
    file1=open(filepath,"r")
    count = 0
    line=file1.readline()
    while (line != ""):
        words = line.split()
        for i in words:
            if i == word:
                count += 1
        line=file1.readline()


    file1.close()
    return count

In [120]:
countWord('C:/Users/DELL/Downloads/16-DAYS-ML/26-Weeks-Of-Data-Science-master/Week-01-Git_&_Python_intro/notebooks/myfile.txt','line')

2

# 32.Validate give string is valid email address.

In [142]:
import re
def validate_email(string):
    if (string != ""):
        if re.findall('@',string):
            return True
        else:
            return False

    else:
        print("invalid email")

In [146]:
validate_email("we@aregreat.com")

True

# 33.Store temperature in celsius for last 7 days of Mumbai in array. Define function where you can pass this array as argument. Convert them in fahrenheit and return array of same.

    Define function 'convert' which will accept array of celsius data.
    Convert each entry into fahrenheit and store in array.
    Function should pass all test cases.

In [147]:
def convert(celsius_data):
    farenhiet = []
    for items in celsius_data:
        farenhiet.append(((items*9)/5)+32)
    return farenhiet

In [148]:
convert([32,31,34,33,29,35,30])

[89.6, 87.8, 93.2, 91.4, 84.2, 95.0, 86.0]

# 34.Write a Python program to convert a list and tuple into arrays using Numpy

In [149]:
import numpy as np

def solution(array1,array2):
    array1=np.append(array1,array2)
    return array1

In [152]:
solution([40, 50, 60],[70, 80, 90])

array([40, 50, 60, 70, 80, 90])

# 35.Write a Python program to reverse an array using Numpy

In [153]:
import numpy as np
def solution(array):
    arr=np.array(array)
    return arr[::-1]

In [155]:
solution([40,50,60,70,80])

array([80, 70, 60, 50, 40])

# 36.Create a 3x3 matrix with values ranging from 2 to 10 using Numpy.

In [156]:
import numpy as np
def solution():
    a=range(2,5)
    b=range(5,8)
    c=range(8,11)
    arr = np.array([a,b,c])
    return arr

In [158]:
solution()

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

# 37.Write a Python program to an array converted to a float type using Numpy

In [159]:
import numpy as np


def solution(array):
    """
    Enter your code here
    """
    arr = np.array(array)
    return arr.astype(float)

In [160]:
solution([40,45,50])

array([40., 45., 50.])

# 38.Write a Python program to convert the values of Fahrenheit degrees into Centigrade degrees. Fahrenheit values are stored into a NumPy array.

In [161]:
import numpy as np

def solution(array):
    return ((np.array(array)-32)*5)/9

In [162]:
solution( [ 0.0,12.0,45.21,34.0,99.91])

array([-17.77777778, -11.11111111,   7.33888889,   1.11111111,
        37.72777778])

# 39.Write a Python program to find common values between two arrays using Numpy

In [163]:
import numpy as np


def solution(array1, array2):
    return np.intersect1d(array1,array2)

In [164]:
solution( [0,10,20,40,60],[10,30,40])

array([10, 40])

# 40.Write a Python program to get the unique elements of an array using Numpy

In [165]:
import numpy as np
def solution(array):
    arr = np.array(array)
    return np.unique(arr)

In [166]:
solution([10,10,20,20,30,30])

array([10, 20, 30])

In [170]:
solution([[1,1],[2,3]])

array([1, 2, 3])

# 41.Write a Python program to convert a tuple into arrays using Numpy.

In [171]:
import numpy as np
def solution(tuple):
    arr = np.array(tuple)
    return arr

In [172]:
solution(([8, 4, 6],[1, 2, 3]))

array([[8, 4, 6],
       [1, 2, 3]])

# 42.Write a Python program to create a 2d array with 1 on the border and 0 inside using Numpy

In [173]:
import numpy as np
def solution(array):
    """
    Enter code here
    """

    array = np.ones((5,5))
    array[1:4,1:4]=0
    return array

In [174]:
solution([[1.,1.,1.,1.,1.],[1.,1.,1.,1.,1.],[1.,1.,1.,1.,1.],[1.,1.,1.,1.,1.],[1.,1.,1.,1.,1.]])

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# 43.Given an array, find the two indices that sum to a specific value.

In [175]:
def two_sum(l1,num):
    if l1 == []:
        raise ValueError
    elif l1 == None:
        raise TypeError
    else:
        for i in range(0,len(l1)):
            for j in range(0,len(l1)):
                if l1[i] + l1[j] == num and i !=j:
                    return [i,j]

In [176]:
two_sum([9,12,5,1,13,18,-12,20,7],16)

[0, 8]

# 44.determine if a string has all unique characters.

In [177]:
def has_unique_chars(string):
    unique_chars = {}
    count = 0
    if string == None:
        return False
    else:
        for letter in string:
            if letter in unique_chars.keys():
                unique_chars[letter] += 1
            else:
                unique_chars[letter] = 1
        for key in unique_chars:
            if unique_chars[key] > 1:
                count += 1
        for value in unique_chars.values():
            if value > 1:
                count += 1
            else:
                pass
        if count > 0:
            return False
        else:
            return True

In [178]:
has_unique_chars("AbkLCsfjXwZmpdFEo")

True

# 45.Determine if a string s1 is a rotation of another string s2, by calling (only once) a function is_rotation.

In [183]:
def is_rotation(s1,s2):
    rotations = []
    if s1 == None:
        if s2 == None:
            return True
        else:
            return False

    elif s1 == '':
        if s2 == '':
            return True
        else:
            return False
    else:

        for i in range(0,len(s1)):
            temp = s1[i:] + s1[:i]
            rotations.append(str(temp))
        if s2 in rotations:
            return True
        else:
            return False

In [186]:
is_rotation('abacd','cdaba')

True

# 46.Compress a string such that 'AAABCCDDDD' becomes 'A3BC2D4'. Only compress the string if it saves space

In [187]:
def compress(s1):
    if s1 is '':
        return ''
    if s1 is None:
        return None
    result = ''
    count = 1
    result += s1[0]
    for i in range(0,len(s1)-1):
        if s1[i] == s1[i+1]:
            count +=1
        elif count >1:
            result += str(count)+s1[i+1]
            count = 1
        elif count == 1:
            result += s1[i+1]
    if(count > 1):
        result += str(count)
    if len(s1) == len(result):
        return s1
    else:
        return result

In [188]:
compress("AABBBCDDEEEE")

'A2B3CD2E4'

# 47.Find the single different char between two strings

In [189]:
def find_diff(s1,s2):
    set1 = set(s1)
    set2 = set(s2)
    return ''.join(str(s) for s in set1^set2)

In [190]:
find_diff('aabcddd','abbbbccde')

'e'

# 48.Lottery:

In [1]:
import random
print('Hi whats your Name?')
#user will input a string
username = input()

generated_number= random.randint(1,20)
print('So {} can you guess the number?' .format(username))

guessed_number = int(input())

        
if generated_number==guessed_number:
    print('win')
else:
    print ('Loose')

Hi whats your Name?
sajib
So sajib can you guess the number?
18
Loose


# 49.Random no(List):

In [2]:
import random
mylst1 = random.sample(range(1,98), 10)
mylst2 = random.sample(range(100,2500), 10)
print(len(mylst1))
print(len(mylst2))
cmblst = mylst1 + mylst2
print(cmblst)

10
10
[27, 30, 62, 7, 73, 92, 89, 14, 95, 53, 1323, 1536, 1036, 1681, 658, 2343, 231, 1225, 1868, 2019]


In [3]:
twicelst = []
i=0
for i in range(0, len(cmblst)):
    twicelst.append(cmblst[i]*2)

print (cmblst)
print (twicelst)

[27, 30, 62, 7, 73, 92, 89, 14, 95, 53, 1323, 1536, 1036, 1681, 658, 2343, 231, 1225, 1868, 2019]
[54, 60, 124, 14, 146, 184, 178, 28, 190, 106, 2646, 3072, 2072, 3362, 1316, 4686, 462, 2450, 3736, 4038]


In [4]:
cmblst.sort()
print(cmblst)

[7, 14, 27, 30, 53, 62, 73, 89, 92, 95, 231, 658, 1036, 1225, 1323, 1536, 1681, 1868, 2019, 2343]


In [5]:
cmblst.sort(reverse=True)
print(cmblst)

[2343, 2019, 1868, 1681, 1536, 1323, 1225, 1036, 658, 231, 95, 92, 89, 73, 62, 53, 30, 27, 14, 7]


# 50.Dictionary operation:

In [6]:
mydict1 ={'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five' : 5}
mydict2 ={'ten': 10, 'nine': 9, 'eight': 8}

In [7]:
print(mydict1.keys())
print(mydict2.values())

dict_keys(['one', 'two', 'three', 'four', 'five'])
dict_values([10, 9, 8])


In [8]:
mydict = {**mydict1, **mydict2}
print(mydict)

{'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five': 5, 'ten': 10, 'nine': 9, 'eight': 8}


In [9]:
mydict1.update(mydict2)

In [10]:
print(mydict1)

{'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five': 5, 'ten': 10, 'nine': 9, 'eight': 8}


In [11]:
import operator
sorted_x = sorted(mydict1.items(), key=operator.itemgetter(1), reverse=False)
print(sorted_x)

[('one', 1), ('two', 2), ('three', 3), ('four', 4), ('five', 5), ('eight', 8), ('nine', 9), ('ten', 10)]


In [12]:
sorted(mydict1.values())

[1, 2, 3, 4, 5, 8, 9, 10]

In [13]:
sorted(mydict1.keys())

['eight', 'five', 'four', 'nine', 'one', 'ten', 'three', 'two']

In [14]:
mydict1.keys()

dict_keys(['one', 'two', 'three', 'four', 'five', 'ten', 'nine', 'eight'])

# 51.Some function exercise:

In [17]:
def divisor():
    for i in range(1,50):
        if(i%7==0):
            print(i)

In [18]:
divisor()

7
14
21
28
35
42
49


In [23]:
from datetime import date
def agecal(yearofbrith, monthofbirth, dateofBirt):
    _dob= date(yearofbrith, monthofbirth, dateofBirt)
    _today = date.today()
    return (_today.year - _dob.year)
    

In [25]:
agecal(1989, 10, 7)

30

In [26]:
def compairlst():
    mylst1 = [1,23,45,10,24]
    mylst2 = [32,23,10,3]
    return list(set(mylst1).intersection(mylst2))

In [27]:
compairlst()

[10, 23]

# palindrome func:

In [28]:
def reverse(s): 
    return s[::-1]

def isPalindrome(stri):
    s= reverse(stri)
    if (s == stri):
        return True
    return False

In [29]:
isPalindrome('madam')

True

In [30]:
def checkisPalindrome(mylst1):
    for i in mylst1:
        if (isPalindrome(i)==False):
            mylst1.remove(i)
    return mylst1

In [31]:
mylst1=['sajib', 'madam', 'navan', 'lamda']
checkisPalindrome(mylst1)

['madam', 'navan']

# unique list

In [32]:
import random
def uniquelist():
    mylst1 = random.sample(range(1,20), 10)
    mylst2 = random.sample(range(10,30), 15)
    return list(set(mylst1).intersection(mylst2))

In [33]:
uniquelist()

[17, 10, 11, 13]

# Fibonacci series:

In [35]:
def recur_fibo(n):
    if n <= 1:
        return n
    else:
        return(recur_fibo(n-1) + recur_fibo(n-2))
nterms = 8
for i in range(nterms):
       print(recur_fibo(i))

0
1
1
2
3
5
8
13


# Password Generator:

In [36]:
def passwordgen(length):
    import random
    import string
    i=0
    pwd=""
    for i in range(length):
        lower=[random.choice(string.ascii_lowercase)]
        upper=[random.choice(string.ascii_uppercase)]
        num= [random.choice(string.digits)]
        punctuation = [random.choice(string.punctuation)]
        allinOne=lower + upper + num + punctuation
        pwd = pwd + random.choice(allinOne)
    print(pwd)

In [37]:
passwordgen(10)

AcL5M<13ui
